### ISSUE TITLE
how to recognize multiple-trace characters

### ISSUE THREAD

**Issue by abubelinha** [jpakkane/glyphtracer#11]
I am trying glyphtracer for the first time but I am not a pro, so maybe these is a ridiculous question:

In my first test, some characters drawn in several traces, like double quotes `"`, are not recognized as a single character (i.e. glyphtracer creates two boxes, one around each single quote).   So, when glyphtracer asks me for the double `quotedbl` glyph I can only select the left or right box, but not both.  See glyphtracer window capture:

![image](https://github.com/jpakkane/glyphtracer/assets/698946/a7f9af26-2f3f-4eb3-ae31-36c1d602ae6b)

On the other hand, symbols like `i`, `!` or `?` are surrounded by a single box, so I can select them as expected.  

Regards
@abubelinha

**Comment by jpakkane** [comment]
The segmentation logic is based on separating lines by finding a row that is "fully white" and then characters by finding a column within the line that is "fully white". The simple solution is to draw a black line under characters that are composed of multiple pieces and then delete the underline in a font editor.

**Comment by abubelinha** [comment]
Thanks for that hint @jpakkane. 
I'll try that.
