### ISSUE TITLE
Any idea why the display is not split into characters?

### ISSUE THREAD

**Issue by jsbien** [jpakkane/glyphtracer#7]
![Screenshot from 2023-04-17 06-42-09](https://user-images.githubusercontent.com/8024702/232383586-e30f56f9-3b9b-45f9-a48b-e82ca4ccd7e5.png)
Looks like the characters has been more or less recognized.
Due to #8 the screenshot is from the autotrace fork (https://github.com/osp/osp.tools.fons). I posted my question here because the problem is addressed explicitly in the "Usage tips".

**Comment by jpakkane** [comment]
Can you post the full image? You can't tell from this one. The most common reason for misdetection is that there is a black bar at one of the edges of the image.

**Comment by jsbien** [comment]
![Ungler1_pismo01_tab112line2_levels-crop lohalo-sharpen-threshold-BW](https://user-images.githubusercontent.com/8024702/232665978-0ecbb834-4083-4602-89e0-c65fa8a2b2ce.png)

**Comment by jpakkane** [comment]
This seems to be working in latest master.

**Comment by jsbien** [comment]
I confirm. Thank you very much!
